### ISSUE TITLE
minor issues with fastlane structure

### ISSUE THREAD

**Issue by IzzySoft** [umer0586/DroidPad#1]
I'm just adding your app to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) – and noticed a few problems with your fastlane tree:

* shortdesc is too long. It's limited to 80 chars by the specs, all beyond that will be truncated. So I locally adjusted that to "controller to transmit commands over WebSocket, MQTT, TCP, and UDP protocols", maybe you simply want to use that.
* fulldesc could use some formatting improvements for better rendering. I made that

```html
Create custom control interfaces easily with a simple drag-and-drop tool and transform your Android device into a remote control by transmitting commands over WebSocket, MQTT, TCP, and UDP protocols.

<b>Key Features:</b>

1. Drag-and-Drop Control Pad Creation:<br>Design your control pads by dragging and dropping components like buttons, sliders, and switches.
2. Multi-Protocol Support and Seamless Server Connections:<br>Easily configure your control pad to act as a client for network protocols such as WebSocket, MQTT, TCP, and UDP. Once configured, the control pad can connect to servers using any of these protocols. Interact with your control pad’s components—like buttons, switches, and sliders—to send real-time commands directly to the connected server and process those commands at server side

For complete guidance please visit https://github.com/umer0586/DroidPad
```

That way it also renders fine as Markdown:

![image](https://github.com/user-attachments/assets/35fd0149-7c5c-458e-8feb-d4725415ee72)

While I'm here: our scanner reported

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

which can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Last point: I was just checking if I can reproduce your APK (for background, please see [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)) – I could not, the dex has quite a few differences. I'm attaching you the diff here so you can take a look for yourself: [diff.zip](https://github.com/user-attachments/files/18369215/diff.zip) The diffoscope will show you the best details. Parts look like coming from optimizer, but I'm not sure. Looking at your Github action I see you're using JDK-19, which is not an LTS release (the interim releases tend to get features added and removed again, and might have some experimental stuff in – better stick with LTS releases there; your app builds fine with JDK-17 and JDK-21, I get identical APKs with both – just not identical to yours. Was your APK built with the Github action? Or could it be you e.g. built it locally without `clean` first, so it used some artifacts from previous builds?

I gladly try to solve this together with you, should you "accept the challenge" :wink:

Thanks in advance, and looking forward to your reply!

**Comment by umer0586** [comment]
I have updated short and full descriptions

> Was your APK built with the Github action? Or could it be you e.g. built it locally without clean first

I built the APK locally without cleaning the project first, which is probably why the `MANIFEST.MF` file is in my APK but not in the one you built.

For the dependency block, I'll just update the `build.gradle` or use `apksigner` .

**Comment by IzzySoft** [comment]
> I have updated short and full descriptions

Thanks! Shortdesc looks fine now, but fulldesc doesn't render correctly:

![image](https://github.com/user-attachments/assets/d97ad2e0-aca6-455b-99da-fdbaa71aedd4)

```markdown
2. <b>Multi-Protocol Support and Flexible Connectivity:</b>
    - For <b>WebSocket, MQTT, TCP, and UDP</b>, the app acts as a client, connecting to servers and enabling real-time interaction through control pad components.  
    - For <b>Bluetooth Low Energy (BLE)</b>, the app acts as a <b>peripheral (GATT server)</b>, notifying interactions such as button presses, slider changes, and switch toggles via BLE notifications.  
```

(i.e. removing the `<br>` and the trailing spaces at the line starting with `2.`, and add an additional leading space to the following bullet-points, making that 4 spaces) would fix that:

![image](https://github.com/user-attachments/assets/d59ecdc1-02af-4935-b6b0-14185e1d6db6)

(ignore the huge spacing between the paragraphs/blocks; this is just a preview where it was made thus intentionally, so "block separation" can be spotted easily)

> I built the APK locally without cleaning the project first

That might explain the diff in the `classes*.dex`.

> which is probably why the MANIFEST.MF file is in my APK but not in the one you built.

No. That's because your APK is signed, and the one I built is not – so that part of the diff is to be expected. Would everything else succeed, the last step would be using `apksigcopier` to copy your signing blocks over to the created APK, and then running `sha256sum` over both APKs if `apksigner` confirmed validity. Then, and only then, both files should have the same checksum – confirming the app to be reproducible.

> For the dependency block, I'll just update the `build.gradle` or use `apksigner`.

Thanks! We meanwhile recommend the former (for transparency, but also so it cannot be forgotten). If you could then build an APK from a clean git tree, I gladly run the check again before your next release. We've also compiled some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) you might wish to look at :wink:

**Comment by umer0586** [comment]
I have updated the full description.

> That might explain the diff in the classes*.dex.

Oh, actually I was looking at the wrong ones. `CERT.RSA` and `CERT.SF` were expected since it's a signed APK.  
I see there is a difference in `classes2.dex` and `baseline.prof` (which could be due to AGP).

I rebuilt the APK locally after running a clean first. The new release has been published.

**Comment by IzzySoft** [comment]
> I have updated the full description.

Thanks! Activated.

> I rebuilt the APK locally after running a clean first. The new release has been published.

And is RB :partying_face: Congrats!

And no more complaints from the scanner either, so I'm closing the issue with this comment. Thanks a lot for your help – and the swift fixes! Fixed even before it went live, wow :smiley:

![image](https://github.com/user-attachments/assets/27dc0d06-22b5-4467-80fe-441d4803339c)
![image](https://github.com/user-attachments/assets/3844ba9d-42ef-45ff-b30b-f62e3e204002)

The "green shield" means RB was confirmed for that version.

Oh, and before I forget: be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [DroidPad at IzzyOnDroid](https://apt.izzysoft.de/packages/com.github.umer0586.droidpad) (will show up at that link with the next sync around 7 pm UTC).

**Comment by IzzySoft** [comment]
@umer0586 v1.6.0 failed RB again. Sure you've built it from a clean tree (and did not forget to clean again)?

**Comment by IzzySoft** [comment]
Oh, and before you ask: please do not replace the APK attached to that release, that has already been distributed. We'd need a new release then (can be a minor maintenance release like `1.6.1`, but must be a separate & new one).

**Comment by umer0586** [comment]
> @umer0586 v1.6.0 failed RB again. Sure you've built it from a clean tree (and did not forget to clean again)?

Yes, My bad! i didn't run clean

**Comment by IzzySoft** [comment]
Oof, again :cry: Then this release will be marked "RB failed", cannot be fixed. Please please please, remember this for all future releases and always make releases from clean trees, yes?

**Comment by IzzySoft** [comment]
And just to let you know: `v1.6.1` was confirmed to be RB again, thanks!

**Comment by umer0586** [comment]
I'll try to set up GitHub Actions for releasing APK, ensuring the APK is always built cleanly.

**Comment by IzzySoft** [comment]
Thanks! Seeing your current `build.yml` with "set up JDK 19", a short hint: Better stick with LTS releases of the JDK (i.e. 11, 17, 21 currently) and avoid the in-between "feature releases". To our experience, the latter often add things which are removed again with the next LTS, so you might become incompatible there (we can only use LTS variants here).

**Comment by umer0586** [comment]
> Thanks! Seeing your current build.yml with "set up JDK 19", a short hint: Better stick with LTS releases of the JDK (i.e. 11, 17, 21 currently) and avoid the in-between "feature releases". To our experience, the latter often add things which are removed again with the next LTS, so you might become incompatible there (we can only use LTS variants here).

Noted !

**Comment by umer0586** [comment]
I published [v1.7.0](https://github.com/umer0586/DroidPad/releases/tag/v1.7.0) about 5 days ago, but it still hasn’t shown up on IzzyOnDroid. How long it usually takes to get updates synced there?

**Comment by IzzySoft** [comment]
> How long it usually takes to get updates synced there?

Update check (and follow-up sync) happen once a day, completing around 7 pm UTC (winter; 6 pm UTC in summer as the server runs on local time, and we still have this stupid switching-around with "daylight saving"). Checks start around 40 min before that, so the updater basically picks up what was made available until around 6:20 pm UTC.

> I published [v1.7.0](https://github.com/umer0586/DroidPad/releases/tag/v1.7.0) about 5 days ago, but it still hasn’t shown up on IzzyOnDroid.

5 **days** ago? That sounds as if something is wrong, let me check…

![Image](https://github.com/user-attachments/assets/3d11ece3-c60f-4ed9-ae93-8430da4fca11)

1.8.0 was picked up yesterday, right after your releasing it.

![Image](https://github.com/user-attachments/assets/067e30cf-523a-452e-be70-4bbfa700c320)

1.7.0 was picked up 2025-01-16 – the day it was released. So all in time. Where are you looking? Maybe your browser caches more than it should, have you tried to (force-)reload the page? https://apt.izzysoft.de/packages/com.github.umer0586.droidpad (or just follow the badge from your Readme) 😉

**Comment by umer0586** [comment]
The page is now displaying the updated version. Previously, I was repeatedly visiting the page where the updates weren’t showing, which led me to ask about it. It might have been a browser caching issue but not sure. 

Thanks

**Comment by IzzySoft** [comment]
Whatever it was: glad it's showing the correct data for you now! Luckily it was not a "global issue" (I'd have heard from many other people otherwise). Enjoy! 😃

**Comment by umer0586** [comment]
Oh! Thanks for pointing that out, I didn’t even notice I missed the "v" prefix in the tag. I’ll make sure to include it next time.

**Comment by umer0586** [comment]
> Done. And Btw, would you like this badge:
> 
> [![RB shield](https://camo.githubusercontent.com/387d98241102168db8857fd3cb5d3a55942afa59d692699817e1419e4cba4a88/68747470733a2f2f736869656c64732e7262746c6f672e6465762f73696d706c652f636f6d2e6769746875622e756d6572303538362e64726f6964706164)](https://shields.rbtlog.dev/com.github.umer0586.droidpad)
> 
> `[<img src="https://shields.rbtlog.dev/simple/com.github.umer0586.droidpad" alt="RB shield">](https://shields.rbtlog.dev/com.github.umer0586.droidpad)`?

Later Maybe

**Comment by IzzySoft** [comment]
Well, it's an offer – not a demand 😄 At your convenience 😉 It will be available when you want it.
